pimcore:
    workflows:
        Product_Workflow:
            enabled: true
            priority: 1
            label: 'Product Workflow'
            initial_place: mode_create
            type: workflow
            supports:
                - \Pimcore\Model\DataObject\Product
                - "subject.gettype() == 'variant'"
            places:
                mode_create:
                    label: 'Creating model'
                    color: '#000000'
                    visibleInHeader: true
                    permissions:
                        -
                            condition: 'has_role(''ROLE_PIMCORE_ADMIN'') or has_role(''ROLE_PRODUCT_CREATOR'')'
                            save: false
                            publish: true
                            delete: false
                            unpublish: false
                            rename: false
                            objectLayout: 1


                Enrich_product:
                    label: 'Add mandatory attributes'
                    color: '#e97325'
                    visibleInHeader: true
                    permissions:
                        -
                            condition: 'has_role(''ROLE_PIMCORE_ADMIN'') or has_role(''ROLE_PRODUCT_CREATOR'')'
                            save: false
                            publish: true
                            delete: false
                            unpublish: false
                            rename: false

                Pending_Review:
                    label: 'In review'
                    color: '#1565d5'
                    visibleInHeader: true
                    permissions:
                        -
                            condition: 'has_role(''ROLE_PIMCORE_ADMIN'') or has_role(''ROLE_PRODUCT_CREATOR'')'
                            save: false
                            publish: true
                            delete: false
                            unpublish: false
                            rename: false


                Pending_Translation:
                    label: 'In translation'
                    color: '#cccccc'
                    visibleInHeader: true
                    permissions:
                        -
                            condition: 'has_role(''ROLE_PIMCORE_ADMIN'') or has_role(''ROLE_PRODUCT_CREATOR'')'
                            save: false
                            publish: true
                            delete: false
                            unpublish: false
                            rename: false

                translation_completed:
                    label: 'Translation complete'
                    color: '#1dcd23'
                    visibleInHeader: true
                    permissions:
                        -
                            condition: 'has_role(''ROLE_PIMCORE_ADMIN'') or has_role(''ROLE_PRODUCT_CREATOR'')'
                            save: false
                            publish: true
                            delete: false
                            unpublish: false
                            rename: false

                open_sku_creation:
                    label: 'Sku creation open'
                    color: '#00ff00'
                    visibleInHeader: false
                    permissions:
                        -
                            condition: 'has_role(''ROLE_PIMCORE_ADMIN'') or has_role(''ROLE_PRODUCT_CREATOR'')'
                            save: false
                            publish: true
                            delete: false
                            unpublish: false
                            rename: false


                sku_created:
                    label: 'Sku created'
                    color: '#1dcd23'
                    visibleInHeader: false
                    permissions:
                        -
                            condition: 'has_role(''ROLE_PIMCORE_ADMIN'') or has_role(''ROLE_PRODUCT_CREATOR'')'
                            save: false
                            publish: true
                            delete: false
                            unpublish: false
                            rename: false

            transitions:

                reject_review:
                    guard: 'is_fully_authenticated() and (has_role(''ROLE_PIMCORE_ADMIN'') or has_role(''ROLE_TRANSLATION_MANAGER''))'
                    from:
                        - Pending_Review
                    to:
                        - Enrich_product
                    options:
                        label: 'Review rejected'
                        changePublishedState: force_published
                        notes:
                            commentEnabled: true
                            additionalFields: {}
                            commentRequired: true
                            type: 'Review'
                        notificationSettings:
                            -
                                notifyRoles: ['Product_creator']
                                channelType:
                                    - pimcore_notification
                    name: reject_review


                reopen_product_enrich:
                    guard: 'is_fully_authenticated() and (has_role(''ROLE_PIMCORE_ADMIN'') or has_role(''ROLE_TRANSLATION_MANAGER''))'
                    from:
                        - translation_completed
                    to:
                        - Enrich_product
                    options:
                        label: 'Release for update'
                        changePublishedState: force_published
                        notes:
                            commentEnabled: true
                            additionalFields: {  }
                            commentRequired: true
                            type: 'Status update'
                        notificationSettings:
                            -
                                notifyRoles: ['Product_creator','Translation_manager']
                                channelType:
                                    - pimcore_notification
                    name: reopen_product_enrich

                translation_done:
                    guard: 'is_fully_authenticated() and (has_role(''ROLE_PIMCORE_ADMIN'') or has_role(''ROLE_TRANSLATION_MANAGER''))'
                    from:
                        - Pending_Translation
                    to:
                        - translation_completed

                    options:
                        label: 'Translation done'
                        changePublishedState: force_published
                        notes:
                            commentEnabled: false
                            additionalFields: {  }
                            commentRequired: false
                            type: 'Translations'
                    name: translation_done

                ready_for_review:
                    guard: 'is_fully_authenticated() and (has_role(''ROLE_PIMCORE_ADMIN'') or has_role(''ROLE_PRODUCT_CREATOR''))'
                    from:
                        - Enrich_product
                    to:
                        - Pending_Review
                    options:
                        label: 'Ready for review'
                        changePublishedState: force_published
                        notes:
                            commentEnabled: false
                            additionalFields: {  }
                            commentRequired: false
                            type: 'Review'
                        notificationSettings:
                            -
                                notifyRoles: ['Translation_manager']
                                channelType:
                                    - pimcore_notification
                    name: ready_for_review

                ready_for_translation:
                    guard: 'is_fully_authenticated() and (has_role(''ROLE_PIMCORE_ADMIN'') or has_role(''ROLE_TRANSLATION_MANAGER''))'
                    from:
                        - Pending_Review
                    to:
                        - Pending_Translation
                    options:
                        label: 'Translate'
                        changePublishedState: force_published
                        notes:
                            commentEnabled: false
                            additionalFields: {  }
                            commentRequired: false
                            type: 'Translations'
                    name: ready_for_translation

                ready_for_translation2:
                    guard: 'is_fully_authenticated() and (has_role(''ROLE_PIMCORE_ADMIN'') or has_role(''ROLE_TRANSLATION_MANAGER''))'
                    from:
                        - Pending_Review
                    to:
                        - Pending_Translation
                    options:
                        label: 'Translate (with TM changes)'
                        changePublishedState: force_published
                        notes:
                            commentEnabled: true
                            commentRequired: true
                            additionalFields:
                                -
                                    name: productTitle
                                    title: Product title changed
                                    fieldType: checkbox
                                -
                                    name: productDescription
                                    title: Product description changed
                                    fieldType: checkbox
                        notificationSettings:
                            -
                                notifyRoles: ['Product_creator']
                                channelType:
                                    - pimcore_notification
                    name: ready_for_translation2

                create_sku:
                    guard: 'is_fully_authenticated() and (has_role(''ROLE_PIMCORE_ADMIN'') or has_role(''ROLE_PRODUCT_CREATOR''))'
                    from:
                        - open_sku_creation
                    to:
                        - open_sku_creation
                        - sku_created
                    options:
                        label: 'Create sku'
                        changePublishedState: force_published
                        notes:
                            commentEnabled: false
                    name: create_sku

                create_done:
                    guard: 'is_fully_authenticated() and (has_role(''ROLE_PIMCORE_ADMIN'') or has_role(''ROLE_PRODUCT_CREATOR''))'
                    from:
                        - mode_create
                    to:
                        - open_sku_creation
                        - Enrich_product
                    options:
                        label: 'Lock model code & Enrich'
                        changePublishedState: force_published
                        notes:
                            commentEnabled: false
                    name: create_done
