framework:
  session:
    handler_id: session.handler.native_file
    save_path: "%kernel.project_dir%/var/sessions/%kernel.environment%"
    cookie_secure: auto
    cookie_samesite: lax
    storage_factory_id: session.storage.factory.native

  csrf_protection:
    enabled: true

  annotations:
    enabled: true
