_pimcore:
  resource: "@PimcoreCoreBundle/config/routing.yaml"

app:
  resource: "../src/Controller/"
  type: annotation

homepage:
  path: /
  controller: App\Controller\DefaultController::indexAction

pimcore_admin_index:
  path: /admin
  controller: Pimcore\Bundle\AdminBundle\Controller\Admin\IndexController::indexAction

pimcore_admin_login:
  path: /admin/login
  controller: Pimcore\Bundle\AdminBundle\Controller\Admin\LoginController::loginAction
