parameters:
  kernel.project_root: "%kernel.project_dir%"
  secret: "%env(APP_SECRET)%"

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $projectDir: "%kernel.project_dir%"

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # Admin User Provider
  Pimcore\Security\User\UserProvider:
    public: true

  # Admin Token Authenticator
  Pimcore\Bundle\AdminBundle\Security\Authenticator\AdminTokenAuthenticator:
    public: true

  App\Service\CartService:
    arguments:
      $requestStack: "@request_stack"

  App\Service\OrderService:
    arguments:
      $entityManager: "@doctrine.orm.entity_manager"
      $cartService: '@App\Service\CartService'

  App\Service\PaymentService:
    arguments:
      $stripeSecretKey: "%env(STRIPE_SECRET_KEY)%"
