pimcore_data_hub:
    configurations:
        dataImport:
            general:
                active: true
                type: dataImporterDataObject
                name: dataImport
                description: ''
                group: ''
                path: null
                modificationDate: 1729010152
                createDate: 1729007199
            loaderConfig:
                type: asset
                settings:
                    assetPath: /flavors.csv
            interpreterConfig:
                type: csv
                settings:
                    skipFirstRow: true
                    delimiter: ','
                    enclosure: '"'
                    escape: \
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: flavor
                loadingStrategy:
                    type: id
                    settings:
                        dataSourceIndex: '0'
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: /Flavor
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: alwaysPublish
            processingConfig:
                executionType: parallel
                idDataIndex: '0'
                cleanup:
                    strategy: unpublish
            mappingConfig:
                -
                    label: 'Code [0]'
                    dataSourceIndex:
                        - '0'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: code
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'Flavor [1]'
                    dataSourceIndex:
                        - '1'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: name
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
            executionConfig:
                scheduleType: recurring
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
